version: '2'
services:

  front-envoy:
    build: .
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    build:
      context: ./docker-nginx-example/tea
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - tea
    environment:
      - SERVICE_NAME=1
    expose:
      - "8080"

  service2:
    build:
      context: ./docker-nginx-example/coffee
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - coffee
    environment:
      - SERVICE_NAME=2
    expose:
      - "8080"

networks:
  envoymesh: {}
